### ISSUE TITLE
Smart Number use cases return 500's

### ISSUE THREAD

**Issue by tbass134** [VonageGarage/VDP#61]
https://vbc-developer.herokuapp.com/smart-numbers/code-snippets/vbc-receive-inbound-call
https://vbc-developer.herokuapp.com/smart-numbers/code-snippets/vbc-route-to-extension

**Comment by fabianrbz** [comment]
@tbass134 that's because they are including a `code_snippet` which doesn't exist. See [here](https://github.com/VonageGarage/VDP/blame/master/_documentation/en/smart-numbers/code-snippets/vbc-receive-inbound-call.md#L12-L170).

In order to fix it, you should either remove the `code-snippet` or add the corresponding file

**Comment by tbass134** [comment]
thanks @fabianrbz  i found the use case code https://developer.nexmo.com/vonage-business-cloud/smart-numbers/code-snippets/vbc-receive-inbound-call 
Does the code go into a file in this location `_examples/voice/receive-an-inbound-call` or should we just add the code snippet directly into the code-snippet page?

**Comment by fabianrbz** [comment]
@tbass134 sorry for the late reply.
yes, the code should  go into a file in `_examples/voice/receive-an-inbound-call`
